[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "sleep 10 && python fix_migrations.py || true && uvicorn app.main:app --host 0.0.0.0 --port $PORT --reload"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10