[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -c 'import os; from alembic.config import Config; from alembic import command; config = Config(\"alembic.ini\"); command.upgrade(config, \"head\")' && uvicorn app.main:app --host 0.0.0.0 --port $PORT --reload"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 