[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"


[deploy]
startCommand = "alembic upgrade head && gunicorn -k uvicorn.workers.UvicornWorker -w 1 app.main:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10