[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python fix_migrations.py && gunicorn -k uvicorn.workers.UvicornWorker -w 2 app.main:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 200
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10