"""remove category from transactions

Revision ID: 168d99495baf
Revises: b304347bc3a2
Create Date: 2025-04-20 03:23:41.846847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168d99495baf'
down_revision: Union[str, None] = 'b304347bc3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
