"""Add user association and more fields to transactions

Revision ID: b304347bc3a2
Revises: 04fce4866d31
Create Date: 2025-04-20 02:40:07.107892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b304347bc3a2'
down_revision: Union[str, None] = '04fce4866d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    payment_method_enum = sa.Enum('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'OTHER', name='paymentmethod')
    payment_method_enum.create(op.get_bind())
    
    # Add columns
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('payment_method', payment_method_enum, nullable=False))
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('recurring_frequency', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'recurring_frequency')
    op.drop_column('transactions', 'is_recurring')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'user_id')
    
    # Drop enum type
    sa.Enum(name='paymentmethod').drop(op.get_bind())
    # ### end Alembic commands ###
